Unify redundant code for correcting unadjustedStaticEval
official-stockfish/Stockfish pull request #4992
Opened 2024-01-15 14:33 UTC by pb00068

passed STC non regression-bounds:
https://tests.stockfishchess.org/tests/live_elo/65a4df6a79aa8af82b970ca0
LLR: 2.94 (-2.94,2.94) <-1.75,0.25>
Total: 43328 W: 11103 L: 10892 D: 21333
Ptnml(0-2): 120, 4920, 11407, 5063, 154

no functional change
bench: 1308279

2024-01-15 14:36 UTC, pb00068 commented
FYI.: another (more simple) version of this passed non-regression bounds too
https://tests.stockfishchess.org/tests/view/65a0f05279aa8af82b96c079
but had merge conficts with PR #4968 , so I had to resubmit.

2024-01-15 14:58 UTC, Disservin requested changes

2024-01-15 14:58 UTC, Disservin commented on src/search.cpp
> +Value to_corrected_static_eval(Value v, Worker* w, const Position& pos) {
Can you use a const reference to the worker here please and use thisThread?

2024-01-17 18:03 UTC, Disservin commented
merged with https://github.com/official-stockfish/Stockfish/commit/0fbad56c50edab533e5a2f0319016d14e6a9f99c, `closes` got lost my bad.

2024-01-17 18:03 UTC, closed without merging