Fix native arch builds on loongarch64, Add support for LSX and LASX
official-stockfish/Stockfish pull request #5600
Opened 2024-09-19 08:54 UTC by WenceyWang

This allows `make -j profile-build` work on loongarch64 and SIMD instruction enabled automatically.

Benchmark on `Loongson-3A6000-HV Not Specified CPU @ 2.5GHz`

```
Total time (ms) : 3959
Nodes searched  : 1011161
Nodes/second    : 255408
```

2024-09-19 10:46 UTC, Disservin commented
Can you add yourself to the authors file please?

2024-09-19 11:23 UTC, WenceyWang commented
> Can you add yourself to the authors file please?

Done.

2024-09-20 09:01 UTC, Disservin requested changes

2024-09-20 09:01 UTC, Disservin commented on src/Makefile
> +	@test "$(lsx)" = "yes" || test "$(lax)" = "no"
`lsx` not `lax`

2024-09-25 17:45 UTC, Disservin approved these changes

2024-09-28 16:01 UTC, closed without merging